services:
  - type: web
    name: king-diadem
    runtime: python
    plan: starter

    buildCommand: pip install -r requirements.txt

    startCommand: python main.py

    envVars:
      - key: CHATGPT_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
